/**
 * AUTO-GENERATED by scripts/download-remote-images.mjs.
 * Do not edit by hand. Run `npm run images:download` after adding remote code images.
 */

export const stockImages = {
  "photo-1432888498266-38ffec3eaf0a": {
    src: "/images/stock/photo-1432888498266-38ffec3eaf0a.webp",
    sourceUrl: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a",
  },
  "photo-1460925895917-afdab827c52f": {
    src: "/images/stock/photo-1460925895917-afdab827c52f.webp",
    sourceUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f",
  },
  "photo-1483985988355-763728e1935b": {
    src: "/images/stock/photo-1483985988355-763728e1935b.webp",
    sourceUrl: "https://images.unsplash.com/photo-1483985988355-763728e1935b",
  },
  "photo-1486312338219-ce68d2c6f44d": {
    src: "/images/stock/photo-1486312338219-ce68d2c6f44d.webp",
    sourceUrl: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d",
  },
  "photo-1498050108023-c5249f4df085": {
    src: "/images/stock/photo-1498050108023-c5249f4df085.webp",
    sourceUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
  },
  "photo-1501504905252-473c47e087f8": {
    src: "/images/stock/photo-1501504905252-473c47e087f8.webp",
    sourceUrl: "https://images.unsplash.com/photo-1501504905252-473c47e087f8",
  },
  "photo-1504384308090-c894fdcc538d": {
    src: "/images/stock/photo-1504384308090-c894fdcc538d.webp",
    sourceUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
  },
  "photo-1504439468489-c8920d796a29": {
    src: "/images/stock/photo-1504439468489-c8920d796a29.webp",
    sourceUrl: "https://images.unsplash.com/photo-1504439468489-c8920d796a29",
  },
  "photo-1504868584819-f8e8b4b6d7e3": {
    src: "/images/stock/photo-1504868584819-f8e8b4b6d7e3.webp",
    sourceUrl: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3",
  },
  "photo-1512941937669-90a1b58e7e9c": {
    src: "/images/stock/photo-1512941937669-90a1b58e7e9c.webp",
    sourceUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c",
  },
  "photo-1514933651103-005eec06c04b": {
    src: "/images/stock/photo-1514933651103-005eec06c04b.webp",
    sourceUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b",
  },
  "photo-1521737711867-e3b97375f902": {
    src: "/images/stock/photo-1521737711867-e3b97375f902.webp",
    sourceUrl: "https://images.unsplash.com/photo-1521737711867-e3b97375f902",
  },
  "photo-1523240795612-9a054b0db644": {
    src: "/images/stock/photo-1523240795612-9a054b0db644.webp",
    sourceUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644",
  },
  "photo-1523275335684-37898b6baf30": {
    src: "/images/stock/photo-1523275335684-37898b6baf30.webp",
    sourceUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
  },
  "photo-1526374965328-7f61d4dc18c5": {
    src: "/images/stock/photo-1526374965328-7f61d4dc18c5.webp",
    sourceUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5",
  },
  "photo-1531973576160-7125cd663d86": {
    src: "/images/stock/photo-1531973576160-7125cd663d86.webp",
    sourceUrl: "https://images.unsplash.com/photo-1531973576160-7125cd663d86",
  },
  "photo-1551288049-bebda4e38f71": {
    src: "/images/stock/photo-1551288049-bebda4e38f71.webp",
    sourceUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71",
  },
  "photo-1551434678-e076c223a692": {
    src: "/images/stock/photo-1551434678-e076c223a692.webp",
    sourceUrl: "https://images.unsplash.com/photo-1551434678-e076c223a692",
  },
  "photo-1552664730-d307ca884978": {
    src: "/images/stock/photo-1552664730-d307ca884978.webp",
    sourceUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978",
  },
  "photo-1553413077-190dd305871c": {
    src: "/images/stock/photo-1553413077-190dd305871c.webp",
    sourceUrl: "https://images.unsplash.com/photo-1553413077-190dd305871c",
  },
  "photo-1556228578-8c89e6adf883": {
    src: "/images/stock/photo-1556228578-8c89e6adf883.webp",
    sourceUrl: "https://images.unsplash.com/photo-1556228578-8c89e6adf883",
  },
  "photo-1556228720-195a672e8a03": {
    src: "/images/stock/photo-1556228720-195a672e8a03.webp",
    sourceUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03",
  },
  "photo-1556742049-0cfed4f6a45d": {
    src: "/images/stock/photo-1556742049-0cfed4f6a45d.webp",
    sourceUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d",
  },
  "photo-1556761175-b413da4baf72": {
    src: "/images/stock/photo-1556761175-b413da4baf72.webp",
    sourceUrl: "https://images.unsplash.com/photo-1556761175-b413da4baf72",
  },
  "photo-1560518883-ce09059eeffa": {
    src: "/images/stock/photo-1560518883-ce09059eeffa.webp",
    sourceUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa",
  },
  "photo-1561070791-2526d30994b5": {
    src: "/images/stock/photo-1561070791-2526d30994b5.webp",
    sourceUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5",
  },
  "photo-1563986768609-322da13575f3": {
    src: "/images/stock/photo-1563986768609-322da13575f3.webp",
    sourceUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3",
  },
  "photo-1571019613454-1cb2f99b2d8b": {
    src: "/images/stock/photo-1571019613454-1cb2f99b2d8b.webp",
    sourceUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b",
  },
  "photo-1576091160399-112ba8d25d1d": {
    src: "/images/stock/photo-1576091160399-112ba8d25d1d.webp",
    sourceUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d",
  },
  "photo-1581092918056-0c4c3acd3789": {
    src: "/images/stock/photo-1581092918056-0c4c3acd3789.webp",
    sourceUrl: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789",
  },
  "photo-1586023492125-27b2c045efd7": {
    src: "/images/stock/photo-1586023492125-27b2c045efd7.webp",
    sourceUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
  },
  "photo-1606326608606-aa0b62935f2b": {
    src: "/images/stock/photo-1606326608606-aa0b62935f2b.webp",
    sourceUrl: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b",
  },
  "photo-1608571423902-eed4a5ad8108": {
    src: "/images/stock/photo-1608571423902-eed4a5ad8108.webp",
    sourceUrl: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108",
  },
} as const;

export type StockImageKey = keyof typeof stockImages;

export function stockImageSrc(key: StockImageKey): string {
  return stockImages[key].src;
}
